### ISSUE TITLE
fibscripts: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by tommyhedley** [mblais/fibery-script-management#1]
There seems to be an issue when pulling rules/buttons with unlink actions. I think it might be a Fibery API problem in that they are not sending args for unlink actions. I receive the following error during pull (the line numbers are off from my console.logs()):

fibscripts: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at validateAutomation (file:///Users/tommy/Documents/Fibery/Script%20Management/Fibscripts/fibery-script-management/src/fibscripts.js:972:42)
    at processFilteredAutomations (file:///Users/tommy/Documents/Fibery/Script%20Management/Fibscripts/fibery-script-management/src/fibscripts.js:1015:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async pull (file:///Users/tommy/Documents/Fibery/Script%20Management/Fibscripts/fibery-script-management/src/fibscripts.js:1054:48)
    at async main (file:///Users/tommy/Documents/Fibery/Script%20Management/Fibscripts/fibery-script-management/src/fibscripts.js:1305:13)

When logging the automation and action in question I get the following respectively: 

**Automation**:  {
  lastRun: { status: 'COMPLETED', startDate: '2023-11-21T02:05:33.534Z' },
  name: 'Option Change',
  type: 'AUTO',
  enabled: true,
  accountName: 'ascent.fibery.io',
  ownerId: '824f5257-50ba-48fe-92af-51bcdab9a186',
  typeId: '51520850-866a-11ee-96e8-cf06f1355172',
  actions: [
    {
      meta: [Object],
      action: 'delete-51520850-866a-11ee-96e8-cf06f1355172',
      args: {},
      id: '4c81a2a8-5e6e-4822-9bed-3a4f800ce07e',
      ownerId: '824f5257-50ba-48fe-92af-51bcdab9a186',
      app: 'fibery'
    },
    {
      meta: [Object],
      action: 'unlink-cbb92690-8701-11ee-8d47-c1fd2c8f84c4',
      id: '024463d3-b3e0-4b14-86c3-6dc8cba213b1',
      ownerId: '824f5257-50ba-48fe-92af-51bcdab9a186',
      app: 'fibery'
    }
  ],
  triggers: [
    {
      trigger: 'updated',
      app: 'fibery',
      args: [Object],
      id: '5700fb98-9f2f-42f1-a83a-9615467bdaf7'
    }
  ],
  created: '2023-11-19T18:28:22.909Z',
  id: '655a53c67f5fce9023921e85'
}

**Action**:  {
  meta: { name: 'Unlink Project', args: [] },
  action: 'unlink-cbb92690-8701-11ee-8d47-c1fd2c8f84c4',
  id: '024463d3-b3e0-4b14-86c3-6dc8cba213b1',
  ownerId: '824f5257-50ba-48fe-92af-51bcdab9a186',
  app: 'fibery'
}

**Comment by mblais** [comment]
Thanks - I added a check for that condition. Not sure if it is an issue or not, but at least now it should not crash fibscripts.
